name: Flutter CI

on:
  pull_request:
    branches:
      - main
      - master
      - develop

  push:
    branches:
      - main
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Check Formatting
        run: dart format --output=none --set-exit-if-changed .

      # - name: Analyze Code
      #   run: flutter analyze

      # - name: Run Tests
        # run: flutter test

      # - name: Build APK
        # run: flutter build apk --debug